name: Test Pull Request

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master


    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: '4.4'

    - name: npm install, test
      working-directory: ./app
      env:
        MONGO_URI: mongodb://localhost/kangaroo?retryWrites=true&w=majority
      run: |
        npm install
        npm run test
